# Generated by Django 4.2.5 on 2023-10-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('song_file', models.FileField(upload_to='songs/')),
                ('image_file', models.FileField(upload_to='images/')),
            ],
        ),
    ]
